Only override Patroni namespace if env var is set
The previous approach did not consider the case where the container may
not have the environment variable set.

We were running into:

      File "/usr/lib/python3/dist-packages/patroni/dcs/__init__.py", line 528, in __init__
        self._base_path = re.sub('/+', '/', '/'.join(['', config.get('namespace', 'service'), config['scope']]))
    TypeError: sequence item 1: expected str instance, dict found

errors because of this.